export const UPDATE_FILES_LIST_PENDING = 'UPDATE_FILES_LIST_PENDING';
export const UPDATE_FILES_LIST_FAILED = 'UPDATE_FILES_LIST_FAILED';
export const UPDATE_FILES_LIST_SUCCESS = 'UPDATE_FILES_LIST_SUCCESS';

export const SEARCH_FILES_BY_NAME = 'SEARCH_FILES_BY_NAME';
